# Generated by Django 5.2.5 on 2025-08-28 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_customuser_church_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
