# Generated by Django 4.2.7 on 2025-08-29 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_customuser_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='church',
            options={'ordering': ['name'], 'verbose_name_plural': 'Churches'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Group', 'verbose_name_plural': 'Groups'},
        ),
        migrations.AlterModelOptions(
            name='newfriend',
            options={'ordering': ['-registration_date'], 'verbose_name': 'New Friend', 'verbose_name_plural': 'New Friends'},
        ),
        migrations.AlterModelOptions(
            name='regularmember',
            options={'ordering': ['user__first_name'], 'verbose_name': 'Regular Member', 'verbose_name_plural': 'Regular Members'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='church',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='members.church'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='current_members_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='group',
            name='max_members',
            field=models.PositiveIntegerField(default=20, help_text='Maximum number of members'),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_day',
            field=models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='group',
            name='meeting_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newfriend',
            name='follow_up_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newfriend',
            name='follow_up_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONTACTED', 'Contacted'), ('FOLLOWED_UP', 'Followed Up'), ('ENGAGED', 'Engaged'), ('NOT_INTERESTED', 'Not Interested')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='newfriend',
            name='invited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_new_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newfriend',
            name='last_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularmember',
            name='availability',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('LIMITED', 'Limited'), ('UNAVAILABLE', 'Unavailable')], default='AVAILABLE', max_length=20),
        ),
        migrations.AddField(
            model_name='regularmember',
            name='baptism_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularmember',
            name='membership_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='regularmember',
            name='spiritual_gifts',
            field=models.TextField(blank=True, help_text='Spiritual gifts and talents'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User Login'), ('LOGOUT', 'User Logout'), ('REGISTER', 'User Registration'), ('PROFILE_UPDATE', 'Profile Update'), ('ROLE_CHANGE', 'Role Change'), ('STATUS_CHANGE', 'Status Change'), ('GROUP_JOIN', 'Group Join'), ('GROUP_LEAVE', 'Group Leave'), ('ATTENDANCE', 'Attendance Recorded'), ('NEW_FRIEND_ADDED', 'New Friend Added'), ('REGULAR_MEMBER_TRANSITION', 'Transitioned to Regular Member'), ('FOLLOW_UP', 'Follow Up Activity')], max_length=30),
        ),
    ]
