# Generated by Django 4.2.7 on 2025-08-29 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_church_options_alter_customuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularmember',
            name='role_type',
            field=models.CharField(choices=[('VSL', 'Vine Servant Leader'), ('CSL', 'Cluster Servant Leader'), ('CL', 'Care Leader'), ('CM', 'Care Member')], max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('VSL', 'Vine Servant Leader'), ('CSL', 'Cluster Servant Leader'), ('CL', 'Care Leader'), ('CM', 'Care Member'), ('NEW_FRIEND', 'New Friend')], max_length=20, unique=True),
        ),
    ]
