# Generated by Django 4.2.7 on 2025-09-05 05:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_regularmember_role_type_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newfriend',
            name='endorsed_to',
            field=models.ForeignKey(blank=True, help_text='The VSL, CSL, or CL who will follow up with this new friend', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsed_new_friends', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('VSL', 'Vine Servant Leader'), ('CSL', 'Cluster Servant Leader'), ('CL', 'Care Leader'), ('CM', 'Care Member'), ('NEW_FRIEND', 'New Friend')], max_length=20, unique=True),
        ),
    ]
