# Generated by Django 4.2.7 on 2025-09-05 06:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_newfriend_endorsed_to_alter_role_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='qr_code_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_type', models.CharField(choices=[('SERVICE', 'Church Service'), ('CARE_GROUP', 'Care Group'), ('MINISTRY', 'Ministry Meeting'), ('EVENT', 'Special Event'), ('OTHER', 'Other')], default='SERVICE', max_length=20)),
                ('date', models.DateField()),
                ('time_in', models.TimeField()),
                ('time_out', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='members.church')),
                ('scanned_by', models.ForeignKey(blank=True, help_text='User who scanned the QR code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanned_attendances', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'ordering': ['-date', '-time_in'],
                'unique_together': {('user', 'date', 'attendance_type')},
            },
        ),
    ]
