# Generated by Django 4.2.7 on 2025-09-05 06:53

from django.db import migrations
import uuid


def generate_unique_qr_codes(apps, schema_editor):
    CustomUser = apps.get_model('members', 'CustomUser')
    for user in CustomUser.objects.filter(qr_code_id__isnull=True):
        user.qr_code_id = uuid.uuid4()
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_customuser_qr_code_id_customuser_qr_code_image_and_more'),
    ]

    operations = [
        migrations.RunPython(generate_unique_qr_codes),
    ]
