# Generated by Django 4.2.7 on 2025-09-05 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20250905_1452'),
        ('members', '0008_auto_20250905_1453'),
    ]

    operations = [
    ]
