# Generated by Django 4.2.7 on 2025-09-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_merge_0008_auto_20250905_1452_0008_auto_20250905_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('SERVICE', 'Church Service'), ('SUNDAY', 'Sunday Service'), ('MIDWEEK', 'Midweek'), ('CHAMP_HARVEST', 'Champ Harvest'), ('CHAMP_YOUTH', 'Champ Youth'), ('CHAMP_YOUNG_ADULT', 'Champ Young Adult'), ('CARE_GROUP', 'Care Group'), ('MINISTRY', 'Ministry Meeting'), ('EVENT', 'Special Event'), ('OTHER', 'Other')], default='SERVICE', max_length=20),
        ),
    ]
