# Generated by Django 4.2.7 on 2025-09-05 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_alter_attendance_attendance_type'),
        ('members', '0011_alter_time_in_field'),
    ]

    operations = [
    ]
