# Generated by Django 4.2.7 on 2025-09-08 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_merge_20250906_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareGroupReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('venue_address', models.TextField(blank=True)),
                ('topic_discussed', models.CharField(blank=True, max_length=200)),
                ('scripture_used', models.CharField(blank=True, max_length=200)),
                ('group_day', models.CharField(blank=True, choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=10)),
                ('group_time', models.TimeField(blank=True, null=True)),
                ('date_of_cg', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('care_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='members.group')),
                ('care_leader', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'CL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cl_reports', to=settings.AUTH_USER_MODEL)),
                ('church', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_group_reports', to='members.church')),
                ('cluster_servant_leader', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'CSL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='csl_reports', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('vine_servant_leader', models.ForeignKey(blank=True, limit_choices_to={'role__name': 'VSL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsl_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Care Group Report',
                'verbose_name_plural': 'Care Group Reports',
                'ordering': ['-date_of_cg', '-created_at'],
                'unique_together': {('care_group', 'date_of_cg')},
            },
        ),
        migrations.CreateModel(
            name='CareGroupMemberReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused')], default='ACTIVE', max_length=10)),
                ('sunday_attendance', models.BooleanField(default=False)),
                ('group_attendance', models.BooleanField(default=False)),
                ('new_disciples_invited', models.PositiveIntegerField(default=0)),
                ('follow_ups', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_group_member_reports', to=settings.AUTH_USER_MODEL)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_reports', to='members.caregroupreport')),
            ],
            options={
                'verbose_name': 'Care Group Member Report',
                'verbose_name_plural': 'Care Group Member Reports',
                'ordering': ['member__first_name', 'member__last_name'],
                'unique_together': {('report', 'member')},
            },
        ),
    ]
