# Generated by Django 4.2.7 on 2025-09-11 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_caregroupreport_caregroupmemberreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='sector',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AlterField(
            model_name='newfriend',
            name='endorsed_to',
            field=models.ForeignKey(blank=True, help_text='The VSL, CSL, CL, or CM who will follow up with this new friend', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endorsed_new_friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
