# Generated by Django 4.2.7 on 2025-10-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_church_sector_alter_newfriend_endorsed_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Required for demographic reporting', max_length=10),
        ),
    ]
