# Generated by Django 4.2.7 on 2025-10-16 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_add_gender_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='google_sheet_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
