# Generated by Django 4.2.7 on 2025-11-02 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_church_google_sheet_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='service_setup',
            field=models.CharField(choices=[('ONSITE', 'Onsite'), ('ONLINE', 'Online')], default='ONSITE', max_length=10),
        ),
    ]
